/**
 * Omnira Trading — a deterministic fixture historical candle source.
 *
 * FIXTURE DATA. NOT A MARKET.
 * ──────────────────────────
 * Every candle here is generated by the same seeded generator the Atlas Market
 * View scenarios use. It reaches no network, models no exchange calendar, and
 * asserts nothing about any real instrument. It exists so the chart's
 * historical navigation can be proven against many pages of candles before a
 * real Market Data Provider exists — and so that when one arrives, the chart's
 * behaviour is already decided and tested.
 *
 * It is the reference implementation of `HistoricalCandleSource`, exactly as
 * the recorded adapter is the reference implementation of the Level-1 provider
 * port. A real source implements the same two methods.
 *
 * WHY ONE LONG SERIES, SLICED
 * ───────────────────────────
 * The whole history for an (instrument, timeframe) is generated ONCE and then
 * paged by slicing. Generating each page separately would make page boundaries
 * discontinuous in price — every join a small cliff that looks like a market
 * event and is not. One series sliced is continuous by construction, and it
 * also makes exhaustion exact: the history ends where the series ends, not
 * where a counter happens to stop.
 *
 * DETERMINISTIC IN THE STRONG SENSE
 * ─────────────────────────────────
 * The seed is derived from the instrument, the timeframe and a fixed label, so
 * the same request always yields the same candles — across calls, across
 * reloads and across processes. No clock is read and no random value is drawn.
 *
 * GATE-08 IS NOT TOUCHED. Requests carry canonical roots (NQ, MNQ, ES). There
 * is no front month, no rollover, no continuous contract and no symbol
 * inference here.
 */

import { toEpochMs } from '../time'
import {
  TIMEFRAME_MINUTES,
  buildCandleSeries,
  seedFrom,
  type MarketCandle,
  type MarketInstrument,
  type MarketTimeframe,
  type Timestamp,
} from '../market-view'
import type {
  HistoricalCandleSource,
  HistoryPage,
  InitialWindowRequest,
  OlderWindowRequest,
} from './history'

/**
 * How much authored history a fixture instrument has.
 *
 * Deliberately finite and deliberately modest: large enough that scrolling back
 * crosses many pages and exercises the merge, small enough that exhaustion is
 * reachable in a manual test rather than theoretical.
 */
export const FIXTURE_HISTORY_LENGTH = 900

/** The opening price of the oldest fixture bar, in whole ticks, per root. */
const START_TICKS: Readonly<Record<MarketInstrument, number>> = {
  NQ: 80_400,
  MNQ: 80_400,
  ES: 22_600,
}

/**
 * The instant the fixture history ENDS at.
 *
 * A written constant, never `Date.now()`. A fixture whose contents depended on
 * when it was read would produce a different chart every day and could not be
 * regression-tested at all.
 */
export const FIXTURE_HISTORY_END: Timestamp = '2026-08-28T15:25:00.000Z' as Timestamp

interface GeneratedHistory {
  readonly candles: readonly MarketCandle[]
}

/**
 * The generated series, memoised per instrument+timeframe.
 *
 * A cache of PURE output: the key fully determines the value, so this changes
 * what the work costs and never what the answer is. It is not shared mutable
 * state in any meaningful sense — clearing it would change nothing observable.
 */
const cache = new Map<string, GeneratedHistory>()

function historyFor(
  instrument: MarketInstrument,
  timeframe: MarketTimeframe,
): GeneratedHistory {
  const key = `${instrument}:${timeframe}`
  const cached = cache.get(key)
  if (cached !== undefined) return cached

  const series = buildCandleSeries({
    seed: seedFrom(`fixture-history:${key}`),
    count: FIXTURE_HISTORY_LENGTH,
    startTicks: START_TICKS[instrument],
    timeframe,
    endTime: FIXTURE_HISTORY_END,
    // A gentle upward drift so a long scroll back looks like a market rather
    // than a flat line. It asserts nothing about any real instrument.
    drift: 0.04,
    volatility: 14,
  })

  const built: GeneratedHistory = { candles: series.candles }
  cache.set(key, built)
  return built
}

/** How the fixture source may be made to misbehave, for testing the chart. */
export interface FixtureHistoryOptions {
  /** Candles per page. A provider may legitimately return fewer than asked. */
  readonly pageSize?: number
  /**
   * Make every `loadBefore` report the provider could not be reached.
   *
   * For proving the chart keeps its candles and stops asking — there is
   * deliberately no option to "return an empty page to mean failure", because
   * that translation is the bug this whole contract exists to prevent.
   */
  readonly unavailableDetail?: string
  /** Make every `loadBefore` fail. Distinct from unavailable, as the states are. */
  readonly errorDetail?: string
  /**
   * Artificial delay, in ms, applied by the caller-supplied scheduler.
   *
   * Used by tests to hold a response open while the instrument changes, so
   * stale-response protection can be exercised deterministically.
   */
  readonly delay?: (signal: { readonly key: string }) => Promise<void>
}

/**
 * Build the fixture historical source.
 *
 * Stateless with respect to requests: it holds no cursor, so two callers cannot
 * interfere and a request cannot depend on which request came before it. The
 * caller says what it already has (`before`), and the source answers from the
 * generated series.
 */
export function createFixtureHistoricalSource(
  options: FixtureHistoryOptions = {},
): HistoricalCandleSource {
  const pageSize = options.pageSize ?? 120

  async function maybeDelay(key: string): Promise<void> {
    if (options.delay !== undefined) await options.delay({ key })
  }

  return {
    label: 'Fixturhistorik',

    async loadInitialWindow(request: InitialWindowRequest): Promise<HistoryPage> {
      await maybeDelay(`${request.instrument}:${request.timeframe}:initial`)
      const { candles } = historyFor(request.instrument, request.timeframe)
      const count = Math.min(request.count, candles.length)
      const window = candles.slice(candles.length - count)
      return {
        outcome: 'PAGE',
        candles: window,
        hasMoreBefore: window.length < candles.length,
      }
    },

    async loadBefore(request: OlderWindowRequest): Promise<HistoryPage> {
      await maybeDelay(`${request.instrument}:${request.timeframe}:before:${request.before}`)

      if (options.errorDetail !== undefined) {
        return { outcome: 'ERROR', detail: options.errorDetail }
      }
      if (options.unavailableDetail !== undefined) {
        return { outcome: 'UNAVAILABLE', detail: options.unavailableDetail }
      }

      const { candles } = historyFor(request.instrument, request.timeframe)

      /*
       * Strictly older, compared as INSTANTS.
       *
       * This used to compare the ISO strings directly, on the same
       * fixed-width reasoning `mergeOlderCandles` used — and it is wrong for
       * the same reason: `Timestamp` permits an optional millisecond field, so
       * `…00:00:00.500Z` sorts BEFORE `…00:00:00Z` as text while being later in
       * time. Every fixture instant this generator produces happens to share
       * one serialization, so the two rules agree today; the point is that the
       * cutoff no longer depends on that happening to stay true.
       */
      const cutoff = candles.findIndex(
        (candle) => toEpochMs(candle.openTime) >= toEpochMs(request.before),
      )
      const available = cutoff === -1 ? candles.length : cutoff

      if (available <= 0) return { outcome: 'EXHAUSTED' }

      const size = Math.min(request.count > 0 ? request.count : pageSize, available)
      const page = candles.slice(available - size, available)

      return {
        outcome: 'PAGE',
        candles: page,
        hasMoreBefore: available - size > 0,
      }
    },
  }
}

/** Bar spacing in milliseconds, for tests that need to reason about instants. */
export function timeframeStepMs(timeframe: MarketTimeframe): number {
  return TIMEFRAME_MINUTES[timeframe] * 60_000
}
