/**
 * Atlas Action Center — what to do next.
 *
 * Not a dashboard: the executive briefing (what happened / cost / what worked)
 * followed by a ranked list of recommended actions derived from real signals
 * (agent activity, costs, leads, social). Generated by the Executive Brain.
 */

import { createClient } from '@/lib/supabase/server'
import { redirect } from 'next/navigation'
import Link from 'next/link'
import { atlasExecutiveSummary } from '@/lib/atlas/executive'
import { OSPage, OSLayer } from '@/components/platform/os'
import { AlertTriangle, ArrowRight, Sparkles } from 'lucide-react'

export const dynamic = 'force-dynamic'
const k = (n: number) => `${Math.round(n)} kr`

const SEV: Record<string, { ring: string; dot: string; label: string }> = {
  critical: { ring: 'border-red-500/30 bg-red-500/[0.05]',     dot: 'bg-red-400',     label: 'Kritisk' },
  high:     { ring: 'border-amber-500/30 bg-amber-500/[0.05]', dot: 'bg-amber-400',   label: 'Hög' },
  normal:   { ring: 'border-border bg-card',                   dot: 'bg-indigo-400',  label: 'Normal' },
}

export default async function AtlasActionCenter() {
  const supabase = await createClient()
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) redirect('/login')

  const exec = await atlasExecutiveSummary()

  return (
    <OSPage className="animate-fade-in">
      <OSLayer layer="hero">
        <div className="flex items-center gap-2 mb-3">
          <Sparkles className="w-4 h-4 text-indigo-300" />
          <span className="eyebrow eyebrow-accent">Atlas · Action Center</span>
        </div>
        <h1 className="text-2xl 2xl:text-3xl font-bold tracking-tight">Vad du bör göra</h1>
        <p className="text-sm text-zinc-400 mt-2">Prioriterat utifrån agentaktivitet, kostnader, leads och social prestanda.</p>
      </OSLayer>

      {/* ── EXECUTIVE BRIEFING ───────────────────────────────────────────── */}
      <OSLayer layer="operational" className="grid grid-cols-1 lg:grid-cols-3 gap-4">
        <Brief title="Vad hände" items={exec.whatHappened} />
        <Brief title="Vad fungerade" items={exec.whatWorked} />
        <div className="rounded-xl border border-border bg-card p-5 space-y-2">
          <p className="eyebrow eyebrow-accent mb-1">Vad det kostade</p>
          <p className="text-sm">Idag: <span className="font-semibold">{k(exec.cost.todaySek)}</span></p>
          <p className="text-sm">Denna månad: <span className="font-semibold">{k(exec.cost.monthSek)}</span></p>
          <p className="text-sm text-muted-foreground">Prognos månad: {k(exec.cost.forecastSek)}</p>
        </div>
      </OSLayer>

      {/* ── PRIORITIZED ACTIONS ──────────────────────────────────────────── */}
      <OSLayer layer="intelligence" className="space-y-3">
        <div>
          <p className="eyebrow eyebrow-accent mb-1">Rekommendationer</p>
          <h2 className="text-base font-semibold tracking-tight">Vad du bör göra härnäst</h2>
        </div>
        <div className="space-y-2.5">
          {exec.whatToDo.map((a, i) => {
            const s = SEV[a.severity] ?? SEV.normal
            return (
              <Link key={i} href={a.href}
                className={`block rounded-xl border ${s.ring} hover:brightness-110 transition-all p-4`}>
                <div className="flex items-start gap-3">
                  <span className={`mt-1.5 w-2 h-2 rounded-full ${s.dot} shrink-0`} />
                  <div className="min-w-0 flex-1">
                    <div className="flex items-center gap-2">
                      {a.severity === 'critical' && <AlertTriangle className="w-3.5 h-3.5 text-red-400" />}
                      <p className="text-sm font-semibold">{a.title}</p>
                      <span className="text-[9px] uppercase tracking-wide text-muted-foreground border border-border rounded-full px-1.5 py-0.5">{s.label}</span>
                    </div>
                    <p className="text-[12px] text-muted-foreground mt-1 leading-relaxed">{a.why}</p>
                  </div>
                  <ArrowRight className="w-4 h-4 text-muted-foreground shrink-0 mt-1" />
                </div>
              </Link>
            )
          })}
        </div>
      </OSLayer>
    </OSPage>
  )
}

function Brief({ title, items }: { title: string; items: string[] }) {
  return (
    <div className="rounded-xl border border-border bg-card p-5 space-y-2">
      <p className="eyebrow eyebrow-accent mb-1">{title}</p>
      {items.map((it, i) => (
        <div key={i} className="flex items-start gap-2">
          <span className="mt-1.5 w-1 h-1 rounded-full bg-zinc-500 shrink-0" />
          <p className="text-sm text-foreground/90 leading-relaxed">{it}</p>
        </div>
      ))}
    </div>
  )
}
