-- Add background music URL column to media_scripts
-- Generated by ElevenLabs sound-generation API, stored in Supabase storage

ALTER TABLE media_scripts
  ADD COLUMN IF NOT EXISTS background_music_url TEXT;
